defaults : &defaults
  adapter: mysql2
  encoding: utf8
  username: root
  password:

development:
  <<: *defaults
  database: storycloud_development

test:
  <<: *defaults
  database: storycloud_test
